import os

ROS_NODE_PLANNER_HOST = os.getenv('ROS_NODE_PLANNER_HOST', 'localhost')
ROS_NODE_PLANNER_PORT = os.getenv('ROS_NODE_PLANNER_PORT', 7501)
ROS_NODE_PLANNER_USE_SSL = os.getenv('ROS_NODE_PLANNER_USE_SSL', False)

ROS_NODE_HUMAN_ACTIVITY_HOST = os.getenv('ROS_NODE_HUMAN_ACTIVITY_HOST', 'localhost')
ROS_NODE_HUMAN_ACTIVITY_PORT = os.getenv('ROS_NODE_HUMAN_ACTIVITY_PORT', 7502)
ROS_NODE_HUMAN_ACTIVITY_USE_SSL = os.getenv('ROS_NODE_HUMAN_ACTIVITY_USE_SSL', False)

ROS_NODE_WORLD_GRAPH_HOST = os.getenv('ROS_NODE_WORLD_GRAPH_HOST', 'localhost')
ROS_NODE_WORLD_GRAPH_PORT = os.getenv('ROS_NODE_WORLD_GRAPH_PORT', 7503)
ROS_NODE_WORLD_GRAPH_USE_SSL = os.getenv('ROS_NODE_WORLD_GRAPH_USE_SSL', False)

ROS_NODE_SKILLS_HOST = os.getenv('ROS_NODE_SKILLS_HOST', 'localhost')
ROS_NODE_SKILLS_PORT = os.getenv('ROS_NODE_SKILLS_PORT', 7504)
ROS_NODE_SKILLS_USE_SSL = os.getenv('ROS_NODE_SKILLS_USE_SSL', False)

# ROS_NODE_SPEECH_HOST = os.getenv('ROS_NODE_SPEECH_HOST', 'ldn-ws-025-ubuntu')
ROS_NODE_SPEECH_HOST = os.getenv('ROS_NODE_SPEECH_HOST', 'localhost') # for siro team
ROS_NODE_SPEECH_PORT = os.getenv('ROS_NODE_SPEECH_PORT', 7505)
ROS_NODE_SPEECH_USE_SSL = os.getenv('ROS_NODE_SPEECH_USE_SSL', False)

# remote NGROK service
#ROS_NODE_SPEECH_HOST = os.getenv('ROS_NODE_SPEECH_HOST', 'diverse-loudly-marlin.ngrok-free.app')
#ROS_NODE_SPEECH_PORT = os.getenv('ROS_NODE_SPEECH_PORT', 443)
#ROS_NODE_SPEECH_USE_SSL = os.getenv('ROS_NODE_SPEECH_USE_SSL', True)
