services:
  siro-server:
    build:
      context: .
      dockerfile: base.dockerfile
      target: siro-server-without-ros-nodes-reconnection
    ports:
      - "7500:7500"
    expose:
      - "7500"